version: '3.8'

services:
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8010:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9091:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - devops

networks:
  devops:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
